import { BASE_URI } from './constants';

const SLOT_ELEMENT_GEM_ID = 1;
const SLOT_SKILL_GEM_ID = 2;
const SLOT_FACTION_GEM_ID = 3;

const SLOT_ELEMENT_GEM_METADATA_URI = `${BASE_URI}/slotElementGemMetadata`;
const SLOT_SKILL_GEM_METADATA_URI = `${BASE_URI}/slotSkillGemMetadata`;
const SLOT_FACTION_GEM_METADATA_URI = `${BASE_URI}/slotFactionGemMetadata`;

const HEAD_COLOR_1_ID = 11;
const HEAD_COLOR_2_ID = 12;
const HEAD_COLOR_3_ID = 13;
const HEAD_COLOR_4_ID = 14;
const HEAD_COLOR_5_ID = 15;
const HEAD_COLOR_6_ID = 16;
const HEAD_COLOR_7_ID = 17;
const HEAD_COLOR_8_ID = 18;
const HEAD_FIRE_ID = 19;
const HEAD_WATER_ID = 20;
const HEAD_EARTH_ID = 21;
const HEAD_AIR_ID = 22;
const HEAD_MAGMA_ID = 23;
const HEAD_ICE_ID = 24;
const HEAD_ROCK_ID = 24;
const HEAD_INVISIBLE_ID = 25;
const HEAD_SKELETTON_ID = 26;
const HEAD_GHOST_ID = 27;
const HEAD_ZOMBIE_ID = 28;
const HEAD_MECHA_ID = 29;

const CHEST_COLOR_1_ID = 31;
const CHEST_COLOR_2_ID = 32;
const CHEST_COLOR_3_ID = 33;
const CHEST_COLOR_4_ID = 34;
const CHEST_COLOR_5_ID = 35;
const CHEST_COLOR_6_ID = 36;
const CHEST_COLOR_7_ID = 37;
const CHEST_COLOR_8_ID = 38;
const CHEST_FIRE_ID = 39;
const CHEST_WATER_ID = 40;
const CHEST_EARTH_ID = 41;
const CHEST_AIR_ID = 42;
const CHEST_MAGMA_ID = 43;
const CHEST_ICE_ID = 44;
const CHEST_ROCK_ID = 45;
const CHEST_INVISIBLE_ID = 46;
const CHEST_SKELETTON_ID = 47;
const CHEST_GHOST_ID = 48;
const CHEST_ZOMBIE_ID = 49;
const CHEST_MECHA_ID = 50;

const BODY_COLOR_1_ID = 51;
const BODY_COLOR_2_ID = 52;
const BODY_COLOR_3_ID = 53;
const BODY_COLOR_4_ID = 54;
const BODY_COLOR_5_ID = 55;
const BODY_COLOR_6_ID = 56;
const BODY_COLOR_7_ID = 57;
const BODY_COLOR_8_ID = 58;
const BODY_FIRE_ID = 59;
const BODY_WATER_ID = 60;
const BODY_EARTH_ID = 61;
const BODY_AIR_ID = 62;
const BODY_MAGMA_ID = 63;
const BODY_ICE_ID = 64;
const BODY_ROCK_ID = 65;
const BODY_INVISIBLE_ID = 66;
const BODY_SKELETTON_ID = 67;
const BODY_GHOST_ID = 68;
const BODY_ZOMBIE_ID = 69;
const BODY_MECHA_ID = 70;

const MOUTH_COLOR_1_ID = 71;
const MOUTH_COLOR_2_ID = 72;
const MOUTH_COLOR_3_ID = 73;
const MOUTH_COLOR_4_ID = 74;
const MOUTH_COLOR_5_ID = 75;
const MOUTH_COLOR_6_ID = 76;
const MOUTH_COLOR_7_ID = 77;
const MOUTH_COLOR_8_ID = 78;
const MOUTH_FIRE_ID = 79;
const MOUTH_WATER_ID = 80;
const MOUTH_EARTH_ID = 81;
const MOUTH_AIR_ID = 82;
const MOUTH_MAGMA_ID = 83;
const MOUTH_ICE_ID = 84;
const MOUTH_ROCK_ID = 85;
const MOUTH_INVISIBLE_ID = 86;
const MOUTH_SKELETTON_ID = 87;
const MOUTH_GHOST_ID = 88;
const MOUTH_ZOMBIE_ID = 89;
const MOUTH_MECHA_ID = 90;

const EYES_COLOR_1_ID = 91;
const EYES_COLOR_2_ID = 92;
const EYES_COLOR_3_ID = 93;
const EYES_COLOR_4_ID = 94;
const EYES_COLOR_5_ID = 95;
const EYES_COLOR_6_ID = 96;
const EYES_COLOR_7_ID = 97;
const EYES_COLOR_8_ID = 98;
const EYES_FIRE_ID = 99;
const EYES_WATER_ID = 100;
const EYES_EARTH_ID = 101;
const EYES_AIR_ID = 102;
const EYES_MAGMA_ID = 103;
const EYES_ICE_ID = 104;
const EYES_ROCK_ID = 105;
const EYES_INVISIBLE_ID = 106;
const EYES_SKELETTON_ID = 107;
const EYES_GHOST_ID = 108;
const EYES_ZOMBIE_ID = 109;
const EYES_MECHA_ID = 110;

const FANGS_COLOR_1_ID = 111;
const FANGS_COLOR_2_ID = 112;
const FANGS_COLOR_3_ID = 113;
const FANGS_COLOR_4_ID = 114;
const FANGS_COLOR_5_ID = 115;
const FANGS_COLOR_6_ID = 116;
const FANGS_COLOR_7_ID = 117;
const FANGS_COLOR_8_ID = 118;
const FANGS_FIRE_ID = 119;
const FANGS_WATER_ID = 120;
const FANGS_EARTH_ID = 121;
const FANGS_AIR_ID = 122;
const FANGS_MAGMA_ID = 123;
const FANGS_ICE_ID = 124;
const FANGS_ROCK_ID = 125;
const FANGS_INVISIBLE_ID = 126;
const FANGS_SKELETTON_ID = 127;
const FANGS_GHOST_ID = 128;
const FANGS_ZOMBIE_ID = 129;
const FANGS_MECHA_ID = 130;

const TAIL_COLOR_1_ID = 131;
const TAIL_COLOR_2_ID = 132;
const TAIL_COLOR_3_ID = 133;
const TAIL_COLOR_4_ID = 134;
const TAIL_COLOR_5_ID = 135;
const TAIL_COLOR_6_ID = 136;
const TAIL_COLOR_7_ID = 137;
const TAIL_COLOR_8_ID = 138;
const TAIL_FIRE_ID = 139;
const TAIL_WATER_ID = 140;
const TAIL_EARTH_ID = 141;
const TAIL_AIR_ID = 142;
const TAIL_MAGMA_ID = 143;
const TAIL_ICE_ID = 144;
const TAIL_ROCK_ID = 145;
const TAIL_INVISIBLE_ID = 146;
const TAIL_SKELETTON_ID = 147;
const TAIL_GHOST_ID = 148;
const TAIL_ZOMBIE_ID = 149;
const TAIL_MECHA_ID = 150;

export {
  SLOT_ELEMENT_GEM_ID,
  SLOT_SKILL_GEM_ID,
  SLOT_FACTION_GEM_ID,
  SLOT_ELEMENT_GEM_METADATA_URI,
  SLOT_SKILL_GEM_METADATA_URI,
  SLOT_FACTION_GEM_METADATA_URI,
  HEAD_COLOR_1_ID,
  HEAD_COLOR_2_ID,
  HEAD_COLOR_3_ID,
  HEAD_COLOR_4_ID,
  HEAD_COLOR_5_ID,
  HEAD_COLOR_6_ID,
  HEAD_COLOR_7_ID,
  HEAD_COLOR_8_ID,
  HEAD_FIRE_ID,
  HEAD_WATER_ID,
  HEAD_EARTH_ID,
  HEAD_AIR_ID,
  HEAD_MAGMA_ID,
  HEAD_ICE_ID,
  HEAD_ROCK_ID,
  HEAD_INVISIBLE_ID,
  HEAD_SKELETTON_ID,
  HEAD_GHOST_ID,
  HEAD_ZOMBIE_ID,
  HEAD_MECHA_ID,
  CHEST_COLOR_1_ID,
  CHEST_COLOR_2_ID,
  CHEST_COLOR_3_ID,
  CHEST_COLOR_4_ID,
  CHEST_COLOR_5_ID,
  CHEST_COLOR_6_ID,
  CHEST_COLOR_7_ID,
  CHEST_COLOR_8_ID,
  CHEST_FIRE_ID,
  CHEST_WATER_ID,
  CHEST_EARTH_ID,
  CHEST_AIR_ID,
  CHEST_MAGMA_ID,
  CHEST_ICE_ID,
  CHEST_ROCK_ID,
  CHEST_INVISIBLE_ID,
  CHEST_SKELETTON_ID,
  CHEST_GHOST_ID,
  CHEST_ZOMBIE_ID,
  CHEST_MECHA_ID,
  BODY_COLOR_1_ID,
  BODY_COLOR_2_ID,
  BODY_COLOR_3_ID,
  BODY_COLOR_4_ID,
  BODY_COLOR_5_ID,
  BODY_COLOR_6_ID,
  BODY_COLOR_7_ID,
  BODY_COLOR_8_ID,
  BODY_FIRE_ID,
  BODY_WATER_ID,
  BODY_EARTH_ID,
  BODY_AIR_ID,
  BODY_MAGMA_ID,
  BODY_ICE_ID,
  BODY_ROCK_ID,
  BODY_INVISIBLE_ID,
  BODY_SKELETTON_ID,
  BODY_GHOST_ID,
  BODY_ZOMBIE_ID,
  BODY_MECHA_ID,
  MOUTH_COLOR_1_ID,
  MOUTH_COLOR_2_ID,
  MOUTH_COLOR_3_ID,
  MOUTH_COLOR_4_ID,
  MOUTH_COLOR_5_ID,
  MOUTH_COLOR_6_ID,
  MOUTH_COLOR_7_ID,
  MOUTH_COLOR_8_ID,
  MOUTH_FIRE_ID,
  MOUTH_WATER_ID,
  MOUTH_EARTH_ID,
  MOUTH_AIR_ID,
  MOUTH_MAGMA_ID,
  MOUTH_ICE_ID,
  MOUTH_ROCK_ID,
  MOUTH_INVISIBLE_ID,
  MOUTH_SKELETTON_ID,
  MOUTH_GHOST_ID,
  MOUTH_ZOMBIE_ID,
  MOUTH_MECHA_ID,
  EYES_COLOR_1_ID,
  EYES_COLOR_2_ID,
  EYES_COLOR_3_ID,
  EYES_COLOR_4_ID,
  EYES_COLOR_5_ID,
  EYES_COLOR_6_ID,
  EYES_COLOR_7_ID,
  EYES_COLOR_8_ID,
  EYES_FIRE_ID,
  EYES_WATER_ID,
  EYES_EARTH_ID,
  EYES_AIR_ID,
  EYES_MAGMA_ID,
  EYES_ICE_ID,
  EYES_ROCK_ID,
  EYES_INVISIBLE_ID,
  EYES_SKELETTON_ID,
  EYES_GHOST_ID,
  EYES_ZOMBIE_ID,
  EYES_MECHA_ID,
  FANGS_COLOR_1_ID,
  FANGS_COLOR_2_ID,
  FANGS_COLOR_3_ID,
  FANGS_COLOR_4_ID,
  FANGS_COLOR_5_ID,
  FANGS_COLOR_6_ID,
  FANGS_COLOR_7_ID,
  FANGS_COLOR_8_ID,
  FANGS_FIRE_ID,
  FANGS_WATER_ID,
  FANGS_EARTH_ID,
  FANGS_AIR_ID,
  FANGS_MAGMA_ID,
  FANGS_ICE_ID,
  FANGS_ROCK_ID,
  FANGS_INVISIBLE_ID,
  FANGS_SKELETTON_ID,
  FANGS_GHOST_ID,
  FANGS_ZOMBIE_ID,
  FANGS_MECHA_ID,
  TAIL_COLOR_1_ID,
  TAIL_COLOR_2_ID,
  TAIL_COLOR_3_ID,
  TAIL_COLOR_4_ID,
  TAIL_COLOR_5_ID,
  TAIL_COLOR_6_ID,
  TAIL_COLOR_7_ID,
  TAIL_COLOR_8_ID,
  TAIL_FIRE_ID,
  TAIL_WATER_ID,
  TAIL_EARTH_ID,
  TAIL_AIR_ID,
  TAIL_MAGMA_ID,
  TAIL_ICE_ID,
  TAIL_ROCK_ID,
  TAIL_INVISIBLE_ID,
  TAIL_SKELETTON_ID,
  TAIL_GHOST_ID,
  TAIL_ZOMBIE_ID,
  TAIL_MECHA_ID,
};
