const BASE_URI_CATALOG = 'ipfs://QmViB6rJTEeJeypDJ9WCS6Q6nPyQ8mfyJmVXqEH2jgxAbq';

const SLOT_ELEMENT_GEM_ID = 1001;
const SLOT_SKILL_GEM_ID = 1002;
const SLOT_FACTION_GEM_ID = 1003;
const SLOT_BACKGROUND_ID = 1004;
const SLOT_HEAD_ID = 1005;
const SLOT_CHEST_ID = 1006;
const SLOT_BODY_ID = 1007;
const SLOT_LEFT_HAND_ID = 1008;
const SLOT_RIGHT_HAND_ID = 1009;
const SLOT_BADGE_1_ID = 1010;
const SLOT_BADGE_2_ID = 1011;
const SLOT_BADGE_3_ID = 1012;
const SLOT_BADGE_4_ID = 1013;
const SLOT_BADGE_5_ID = 1014;
const SLOT_EXTRA_1_ID = 1015;
const SLOT_EXTRA_2_ID = 1016;
const SLOT_EXTRA_3_ID = 1017;
const SLOT_EXTRA_4_ID = 1018;
const SLOT_EXTRA_5_ID = 1019;

const Z_INDEX_BACKGROUND_SLOT = 1;
const Z_INDEX_FRAME_FIXED = 3;
const Z_INDEX_HEAD_FIXED = 5;
const Z_INDEX_BODY_FIXED = 7;
const Z_INDEX_RIB_FIXED = 9;
const Z_INDEX_CHEST_FIXED = 11;
const Z_INDEX_CHEEK_FIXED = 13;
const Z_INDEX_JAW_FIXED = 15;
const Z_INDEX_EYE_FIXED = 17;
const Z_INDEX_FANGS_FIXED = 19;
const Z_INDEX_RATTLE_FIXED = 21;
const Z_INDEX_TONGUE_FIXED = 23;
const Z_INDEX_HEAD_SLOT = 25;
const Z_INDEX_CHEST_SLOT = 27;
const Z_INDEX_BODY_SLOT = 29;
const Z_INDEX_RIGHT_HAND_SLOT = 31;
const Z_INDEX_LEFT_HAND_SLOT = 33;
const Z_INDEX_FINGERS_FIXED = 35;
const Z_INDEX_BADGE_SLOT = 37;
const Z_INDEX_EXTRA_SLOT = 39;
const Z_INDEX_ELEMENT_GEM_SLOT = 41;
const Z_INDEX_SKILL_GEM_SLOT = 43;
const Z_INDEX_FACTION_GEM_SLOT = 43;

const CATALOG_METADATA_URI = `${BASE_URI_CATALOG}/Catalog.json`;
const CATALOG_TYPE = 'img/png';
const SLOT_BACKGROUND_METADATA_URI = `${BASE_URI_CATALOG}/slots/background.json`;
const SLOT_ELEMENT_GEM_METADATA_URI = `${BASE_URI_CATALOG}/slots/elementGem.json`;
const SLOT_SKILL_GEM_METADATA_URI = `${BASE_URI_CATALOG}/slots/skillGem.json`;
const SLOT_FACTION_GEM_METADATA_URI = `${BASE_URI_CATALOG}/slots/factionGem.json`;
const SLOT_HEAD_METADATA_URI = `${BASE_URI_CATALOG}/slots/head.json`;
const SLOT_CHEST_METADATA_URI = `${BASE_URI_CATALOG}/slots/chest.json`;
const SLOT_BODY_METADATA_URI = `${BASE_URI_CATALOG}/slots/body.json`;
const SLOT_LEFT_HAND_METADATA_URI = `${BASE_URI_CATALOG}/slots/leftHand.json`;
const SLOT_RIGHT_HAND_METADATA_URI = `${BASE_URI_CATALOG}/slots/rightHand.json`;
const SLOT_BADGE_METADATA_URI = `${BASE_URI_CATALOG}/slots/badge.json`;
const SLOT_EXTRA_METADATA_URI = `${BASE_URI_CATALOG}/slots/extra.json`;

export {
  BASE_URI_CATALOG,
  SLOT_ELEMENT_GEM_ID,
  SLOT_SKILL_GEM_ID,
  SLOT_FACTION_GEM_ID,
  SLOT_BACKGROUND_ID,
  SLOT_HEAD_ID,
  SLOT_CHEST_ID,
  SLOT_BODY_ID,
  SLOT_LEFT_HAND_ID,
  SLOT_RIGHT_HAND_ID,
  SLOT_BADGE_1_ID,
  SLOT_BADGE_2_ID,
  SLOT_BADGE_3_ID,
  SLOT_BADGE_4_ID,
  SLOT_BADGE_5_ID,
  SLOT_EXTRA_1_ID,
  SLOT_EXTRA_2_ID,
  SLOT_EXTRA_3_ID,
  SLOT_EXTRA_4_ID,
  SLOT_EXTRA_5_ID,
  Z_INDEX_BACKGROUND_SLOT,
  Z_INDEX_FRAME_FIXED,
  Z_INDEX_HEAD_FIXED,
  Z_INDEX_BODY_FIXED,
  Z_INDEX_RIB_FIXED,
  Z_INDEX_CHEST_FIXED,
  Z_INDEX_JAW_FIXED,
  Z_INDEX_CHEEK_FIXED,
  Z_INDEX_EYE_FIXED,
  Z_INDEX_FANGS_FIXED,
  Z_INDEX_RATTLE_FIXED,
  Z_INDEX_TONGUE_FIXED,
  Z_INDEX_HEAD_SLOT,
  Z_INDEX_CHEST_SLOT,
  Z_INDEX_BODY_SLOT,
  Z_INDEX_RIGHT_HAND_SLOT,
  Z_INDEX_LEFT_HAND_SLOT,
  Z_INDEX_FINGERS_FIXED,
  Z_INDEX_BADGE_SLOT,
  Z_INDEX_EXTRA_SLOT,
  Z_INDEX_ELEMENT_GEM_SLOT,
  Z_INDEX_SKILL_GEM_SLOT,
  Z_INDEX_FACTION_GEM_SLOT,
  CATALOG_METADATA_URI,
  CATALOG_TYPE,
  SLOT_BACKGROUND_METADATA_URI,
  SLOT_ELEMENT_GEM_METADATA_URI,
  SLOT_SKILL_GEM_METADATA_URI,
  SLOT_FACTION_GEM_METADATA_URI,
  SLOT_HEAD_METADATA_URI,
  SLOT_CHEST_METADATA_URI,
  SLOT_BODY_METADATA_URI,
  SLOT_LEFT_HAND_METADATA_URI,
  SLOT_RIGHT_HAND_METADATA_URI,
  SLOT_BADGE_METADATA_URI,
  SLOT_EXTRA_METADATA_URI,
};
