import { bn, BASE_URI } from './constants';

const SLOT_ELEMENT_GEM_ID = bn(1);
const SLOT_SKILL_GEM_ID = bn(2);
const SLOT_FACTION_GEM_ID = bn(3);

const SLOT_ELEMENT_GEM_METADATA_URI = `${BASE_URI}/slotElementGemMetadata`;
const SLOT_SKILL_GEM_METADATA_URI = `${BASE_URI}/slotSkillGemMetadata`;
const SLOT_FACTION_GEM_METADATA_URI = `${BASE_URI}/slotFactionGemMetadata`;

const HEAD_COLOR_1_ID = bn(11);
const HEAD_COLOR_2_ID = bn(12);
const HEAD_COLOR_3_ID = bn(13);
const HEAD_COLOR_4_ID = bn(14);
const HEAD_COLOR_5_ID = bn(15);
const HEAD_COLOR_6_ID = bn(16);
const HEAD_COLOR_7_ID = bn(17);
const HEAD_COLOR_8_ID = bn(18);
const HEAD_FIRE_ID = bn(19);
const HEAD_WATER_ID = bn(20);
const HEAD_EARTH_ID = bn(21);
const HEAD_AIR_ID = bn(22);
const HEAD_MAGMA_ID = bn(23);
const HEAD_ICE_ID = bn(24);
const HEAD_ROCK_ID = bn(24);
const HEAD_INVISIBLE_ID = bn(25);
const HEAD_SKELETTON_ID = bn(26);
const HEAD_GHOST_ID = bn(27);
const HEAD_ZOMBIE_ID = bn(28);
const HEAD_MECHA_ID = bn(29);

const CHEST_COLOR_1_ID = bn(31);
const CHEST_COLOR_2_ID = bn(32);
const CHEST_COLOR_3_ID = bn(33);
const CHEST_COLOR_4_ID = bn(34);
const CHEST_COLOR_5_ID = bn(35);
const CHEST_COLOR_6_ID = bn(36);
const CHEST_COLOR_7_ID = bn(37);
const CHEST_COLOR_8_ID = bn(38);
const CHEST_FIRE_ID = bn(39);
const CHEST_WATER_ID = bn(40);
const CHEST_EARTH_ID = bn(41);
const CHEST_AIR_ID = bn(42);
const CHEST_MAGMA_ID = bn(43);
const CHEST_ICE_ID = bn(44);
const CHEST_ROCK_ID = bn(45);
const CHEST_INVISIBLE_ID = bn(46);
const CHEST_SKELETTON_ID = bn(47);
const CHEST_GHOST_ID = bn(48);
const CHEST_ZOMBIE_ID = bn(49);
const CHEST_MECHA_ID = bn(50);

const BODY_COLOR_1_ID = bn(51);
const BODY_COLOR_2_ID = bn(52);
const BODY_COLOR_3_ID = bn(53);
const BODY_COLOR_4_ID = bn(54);
const BODY_COLOR_5_ID = bn(55);
const BODY_COLOR_6_ID = bn(56);
const BODY_COLOR_7_ID = bn(57);
const BODY_COLOR_8_ID = bn(58);
const BODY_FIRE_ID = bn(59);
const BODY_WATER_ID = bn(60);
const BODY_EARTH_ID = bn(61);
const BODY_AIR_ID = bn(62);
const BODY_MAGMA_ID = bn(63);
const BODY_ICE_ID = bn(64);
const BODY_ROCK_ID = bn(65);
const BODY_INVISIBLE_ID = bn(66);
const BODY_SKELETTON_ID = bn(67);
const BODY_GHOST_ID = bn(68);
const BODY_ZOMBIE_ID = bn(69);
const BODY_MECHA_ID = bn(70);

const MOUTH_COLOR_1_ID = bn(71);
const MOUTH_COLOR_2_ID = bn(72);
const MOUTH_COLOR_3_ID = bn(73);
const MOUTH_COLOR_4_ID = bn(74);
const MOUTH_COLOR_5_ID = bn(75);
const MOUTH_COLOR_6_ID = bn(76);
const MOUTH_COLOR_7_ID = bn(77);
const MOUTH_COLOR_8_ID = bn(78);
const MOUTH_FIRE_ID = bn(79);
const MOUTH_WATER_ID = bn(80);
const MOUTH_EARTH_ID = bn(81);
const MOUTH_AIR_ID = bn(82);
const MOUTH_MAGMA_ID = bn(83);
const MOUTH_ICE_ID = bn(84);
const MOUTH_ROCK_ID = bn(85);
const MOUTH_INVISIBLE_ID = bn(86);
const MOUTH_SKELETTON_ID = bn(87);
const MOUTH_GHOST_ID = bn(88);
const MOUTH_ZOMBIE_ID = bn(89);
const MOUTH_MECHA_ID = bn(90);

const EYES_COLOR_1_ID = bn(91);
const EYES_COLOR_2_ID = bn(92);
const EYES_COLOR_3_ID = bn(93);
const EYES_COLOR_4_ID = bn(94);
const EYES_COLOR_5_ID = bn(95);
const EYES_COLOR_6_ID = bn(96);
const EYES_COLOR_7_ID = bn(97);
const EYES_COLOR_8_ID = bn(98);
const EYES_FIRE_ID = bn(99);
const EYES_WATER_ID = bn(100);
const EYES_EARTH_ID = bn(101);
const EYES_AIR_ID = bn(102);
const EYES_MAGMA_ID = bn(103);
const EYES_ICE_ID = bn(104);
const EYES_ROCK_ID = bn(105);
const EYES_INVISIBLE_ID = bn(106);
const EYES_SKELETTON_ID = bn(107);
const EYES_GHOST_ID = bn(108);
const EYES_ZOMBIE_ID = bn(109);
const EYES_MECHA_ID = bn(110);

const FANGS_COLOR_1_ID = bn(111);
const FANGS_COLOR_2_ID = bn(112);
const FANGS_COLOR_3_ID = bn(113);
const FANGS_COLOR_4_ID = bn(114);
const FANGS_COLOR_5_ID = bn(115);
const FANGS_COLOR_6_ID = bn(116);
const FANGS_COLOR_7_ID = bn(117);
const FANGS_COLOR_8_ID = bn(118);
const FANGS_FIRE_ID = bn(119);
const FANGS_WATER_ID = bn(120);
const FANGS_EARTH_ID = bn(121);
const FANGS_AIR_ID = bn(122);
const FANGS_MAGMA_ID = bn(123);
const FANGS_ICE_ID = bn(124);
const FANGS_ROCK_ID = bn(125);
const FANGS_INVISIBLE_ID = bn(126);
const FANGS_SKELETTON_ID = bn(127);
const FANGS_GHOST_ID = bn(128);
const FANGS_ZOMBIE_ID = bn(129);
const FANGS_MECHA_ID = bn(130);

const TAIL_COLOR_1_ID = bn(131);
const TAIL_COLOR_2_ID = bn(132);
const TAIL_COLOR_3_ID = bn(133);
const TAIL_COLOR_4_ID = bn(134);
const TAIL_COLOR_5_ID = bn(135);
const TAIL_COLOR_6_ID = bn(136);
const TAIL_COLOR_7_ID = bn(137);
const TAIL_COLOR_8_ID = bn(138);
const TAIL_FIRE_ID = bn(139);
const TAIL_WATER_ID = bn(140);
const TAIL_EARTH_ID = bn(141);
const TAIL_AIR_ID = bn(142);
const TAIL_MAGMA_ID = bn(143);
const TAIL_ICE_ID = bn(144);
const TAIL_ROCK_ID = bn(145);
const TAIL_INVISIBLE_ID = bn(146);
const TAIL_SKELETTON_ID = bn(147);
const TAIL_GHOST_ID = bn(148);
const TAIL_ZOMBIE_ID = bn(149);
const TAIL_MECHA_ID = bn(150);

export {
  SLOT_ELEMENT_GEM_ID,
  SLOT_SKILL_GEM_ID,
  SLOT_FACTION_GEM_ID,
  SLOT_ELEMENT_GEM_METADATA_URI,
  SLOT_SKILL_GEM_METADATA_URI,
  SLOT_FACTION_GEM_METADATA_URI,
  HEAD_COLOR_1_ID,
  HEAD_COLOR_2_ID,
  HEAD_COLOR_3_ID,
  HEAD_COLOR_4_ID,
  HEAD_COLOR_5_ID,
  HEAD_COLOR_6_ID,
  HEAD_COLOR_7_ID,
  HEAD_COLOR_8_ID,
  HEAD_FIRE_ID,
  HEAD_WATER_ID,
  HEAD_EARTH_ID,
  HEAD_AIR_ID,
  HEAD_MAGMA_ID,
  HEAD_ICE_ID,
  HEAD_ROCK_ID,
  HEAD_INVISIBLE_ID,
  HEAD_SKELETTON_ID,
  HEAD_GHOST_ID,
  HEAD_ZOMBIE_ID,
  HEAD_MECHA_ID,
  CHEST_COLOR_1_ID,
  CHEST_COLOR_2_ID,
  CHEST_COLOR_3_ID,
  CHEST_COLOR_4_ID,
  CHEST_COLOR_5_ID,
  CHEST_COLOR_6_ID,
  CHEST_COLOR_7_ID,
  CHEST_COLOR_8_ID,
  CHEST_FIRE_ID,
  CHEST_WATER_ID,
  CHEST_EARTH_ID,
  CHEST_AIR_ID,
  CHEST_MAGMA_ID,
  CHEST_ICE_ID,
  CHEST_ROCK_ID,
  CHEST_INVISIBLE_ID,
  CHEST_SKELETTON_ID,
  CHEST_GHOST_ID,
  CHEST_ZOMBIE_ID,
  CHEST_MECHA_ID,
  BODY_COLOR_1_ID,
  BODY_COLOR_2_ID,
  BODY_COLOR_3_ID,
  BODY_COLOR_4_ID,
  BODY_COLOR_5_ID,
  BODY_COLOR_6_ID,
  BODY_COLOR_7_ID,
  BODY_COLOR_8_ID,
  BODY_FIRE_ID,
  BODY_WATER_ID,
  BODY_EARTH_ID,
  BODY_AIR_ID,
  BODY_MAGMA_ID,
  BODY_ICE_ID,
  BODY_ROCK_ID,
  BODY_INVISIBLE_ID,
  BODY_SKELETTON_ID,
  BODY_GHOST_ID,
  BODY_ZOMBIE_ID,
  BODY_MECHA_ID,
  MOUTH_COLOR_1_ID,
  MOUTH_COLOR_2_ID,
  MOUTH_COLOR_3_ID,
  MOUTH_COLOR_4_ID,
  MOUTH_COLOR_5_ID,
  MOUTH_COLOR_6_ID,
  MOUTH_COLOR_7_ID,
  MOUTH_COLOR_8_ID,
  MOUTH_FIRE_ID,
  MOUTH_WATER_ID,
  MOUTH_EARTH_ID,
  MOUTH_AIR_ID,
  MOUTH_MAGMA_ID,
  MOUTH_ICE_ID,
  MOUTH_ROCK_ID,
  MOUTH_INVISIBLE_ID,
  MOUTH_SKELETTON_ID,
  MOUTH_GHOST_ID,
  MOUTH_ZOMBIE_ID,
  MOUTH_MECHA_ID,
  EYES_COLOR_1_ID,
  EYES_COLOR_2_ID,
  EYES_COLOR_3_ID,
  EYES_COLOR_4_ID,
  EYES_COLOR_5_ID,
  EYES_COLOR_6_ID,
  EYES_COLOR_7_ID,
  EYES_COLOR_8_ID,
  EYES_FIRE_ID,
  EYES_WATER_ID,
  EYES_EARTH_ID,
  EYES_AIR_ID,
  EYES_MAGMA_ID,
  EYES_ICE_ID,
  EYES_ROCK_ID,
  EYES_INVISIBLE_ID,
  EYES_SKELETTON_ID,
  EYES_GHOST_ID,
  EYES_ZOMBIE_ID,
  EYES_MECHA_ID,
  FANGS_COLOR_1_ID,
  FANGS_COLOR_2_ID,
  FANGS_COLOR_3_ID,
  FANGS_COLOR_4_ID,
  FANGS_COLOR_5_ID,
  FANGS_COLOR_6_ID,
  FANGS_COLOR_7_ID,
  FANGS_COLOR_8_ID,
  FANGS_FIRE_ID,
  FANGS_WATER_ID,
  FANGS_EARTH_ID,
  FANGS_AIR_ID,
  FANGS_MAGMA_ID,
  FANGS_ICE_ID,
  FANGS_ROCK_ID,
  FANGS_INVISIBLE_ID,
  FANGS_SKELETTON_ID,
  FANGS_GHOST_ID,
  FANGS_ZOMBIE_ID,
  FANGS_MECHA_ID,
  TAIL_COLOR_1_ID,
  TAIL_COLOR_2_ID,
  TAIL_COLOR_3_ID,
  TAIL_COLOR_4_ID,
  TAIL_COLOR_5_ID,
  TAIL_COLOR_6_ID,
  TAIL_COLOR_7_ID,
  TAIL_COLOR_8_ID,
  TAIL_FIRE_ID,
  TAIL_WATER_ID,
  TAIL_EARTH_ID,
  TAIL_AIR_ID,
  TAIL_MAGMA_ID,
  TAIL_ICE_ID,
  TAIL_ROCK_ID,
  TAIL_INVISIBLE_ID,
  TAIL_SKELETTON_ID,
  TAIL_GHOST_ID,
  TAIL_ZOMBIE_ID,
  TAIL_MECHA_ID,
};
