const BASE_URI = 'https://ABC';
const ELEMENT_GEM_METADATA = `${BASE_URI}/elementGemMetadata`;
const ELEMENT_GEM_DEFAULT_URI = `${BASE_URI}/elementGemDefaultUri`;
const SKILL_GEM_METADATA = `${BASE_URI}/skillGemMetadata`;
const SKILL_GEM_DEFAULT_URI = `${BASE_URI}/skillGemDefaultUri`;
const FACTION_GEM_METADATA = `${BASE_URI}/factionGemMetadata`;
const FACTION_GEM_DEFAULT_URI = `${BASE_URI}/factionGemDefaultUri`;
const SNAKE_METADATA_URI = `${BASE_URI}/snakeMetadata`;
const SNAKE_DEFAULT_URI = `${BASE_URI}/snakeDefaultUri`;
const CATALOG_METADATA_URI = `${BASE_URI}/catalogMetadata`;
const CATALOG_TYPE = 'img/png';
const MAX_GIFTS_PER_PHASE = 10;
const MAX_SUPPLY_FOR_GEMS = 5000;

const ASSET_ID_SOLDIER_EGG = 1;
const ASSET_ID_COMMANDER_EGG = 2;
const ASSET_ID_GENERAL_EGG = 3;
const ASSET_ID_SOLDIER_EGG_FIRE = 4;
const ASSET_ID_SOLDIER_EGG_EARTH = 5;
const ASSET_ID_SOLDIER_EGG_WATER = 6;
const ASSET_ID_SOLDIER_EGG_AIR = 7;
const ASSET_ID_COMMANDER_EGG_FIRE = 8;
const ASSET_ID_COMMANDER_EGG_EARTH = 9;
const ASSET_ID_COMMANDER_EGG_WATER = 10;
const ASSET_ID_COMMANDER_EGG_AIR = 11;
const ASSET_ID_GENERAL_EGG_FIRE = 12;
const ASSET_ID_GENERAL_EGG_EARTH = 13;
const ASSET_ID_GENERAL_EGG_WATER = 14;
const ASSET_ID_GENERAL_EGG_AIR = 15;

export {
  BASE_URI,
  ELEMENT_GEM_METADATA,
  ELEMENT_GEM_DEFAULT_URI,
  SKILL_GEM_METADATA,
  SKILL_GEM_DEFAULT_URI,
  FACTION_GEM_METADATA,
  FACTION_GEM_DEFAULT_URI,
  SNAKE_METADATA_URI,
  SNAKE_DEFAULT_URI,
  MAX_GIFTS_PER_PHASE,
  MAX_SUPPLY_FOR_GEMS,
  CATALOG_METADATA_URI,
  CATALOG_TYPE,
  ASSET_ID_SOLDIER_EGG,
  ASSET_ID_COMMANDER_EGG,
  ASSET_ID_GENERAL_EGG,
  ASSET_ID_SOLDIER_EGG_FIRE,
  ASSET_ID_SOLDIER_EGG_EARTH,
  ASSET_ID_SOLDIER_EGG_WATER,
  ASSET_ID_SOLDIER_EGG_AIR,
  ASSET_ID_COMMANDER_EGG_FIRE,
  ASSET_ID_COMMANDER_EGG_EARTH,
  ASSET_ID_COMMANDER_EGG_WATER,
  ASSET_ID_COMMANDER_EGG_AIR,
  ASSET_ID_GENERAL_EGG_FIRE,
  ASSET_ID_GENERAL_EGG_EARTH,
  ASSET_ID_GENERAL_EGG_WATER,
  ASSET_ID_GENERAL_EGG_AIR,
};
