const BASE_URI = 'https://ABC';
const ELEMENT_GEM_METADATA = `${BASE_URI}/elementGemMetadata`;
const ELEMENT_GEM_DEFAULT_URI = `${BASE_URI}/elementGemDefaultUri`;
const SKILL_GEM_METADATA = `${BASE_URI}/skillGemMetadata`;
const SKILL_GEM_DEFAULT_URI = `${BASE_URI}/skillGemDefaultUri`;
const FACTION_GEM_METADATA = `${BASE_URI}/factionGemMetadata`;
const FACTION_GEM_DEFAULT_URI = `${BASE_URI}/factionGemDefaultUri`;
const SNAKE_METADATA_URI = `${BASE_URI}/snakeMetadata`;
const SNAKE_DEFAULT_URI = `${BASE_URI}/snakeDefaultUri`;
const CATALOG_METADATA_URI = `${BASE_URI}/catalogMetadata`;
const CATALOG_TYPE = 'img/png';
const MAX_GIFTS_PER_PHASE = 10;
const MAX_SUPPLY_FOR_GEMS = 5000;

export {
  BASE_URI,
  ELEMENT_GEM_METADATA,
  ELEMENT_GEM_DEFAULT_URI,
  SKILL_GEM_METADATA,
  SKILL_GEM_DEFAULT_URI,
  FACTION_GEM_METADATA,
  FACTION_GEM_DEFAULT_URI,
  SNAKE_METADATA_URI,
  SNAKE_DEFAULT_URI,
  MAX_GIFTS_PER_PHASE,
  MAX_SUPPLY_FOR_GEMS,
  CATALOG_METADATA_URI,
  CATALOG_TYPE,
};
